export const FLAVORS = [
  {
    id: 'crimson-berry',
    name: 'Crimson Berry',
    tagline: 'Raw Power.',
    accent: '#dc2626',
    accentRgb: '220, 38, 38',
    canColor: '#8b0000',
    labelColor: '#dc2626',
    bg: '#fff5f5',
    ingredients: ['Strawberry', 'Raspberry', 'Taurine', 'Vitamin B12'],
    emoji: '🍓',
    nutrition: {
      calories: 160,
      protein: '20g',
      caffeine: '150mg',
      sugar: '2g',
      sodium: '80mg',
    },
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate',
    tagline: 'Pure Intensity.',
    accent: '#78350f',
    accentRgb: '120, 53, 15',
    canColor: '#1c0a00',
    labelColor: '#92400e',
    bg: '#fffbeb',
    ingredients: ['Cacao', 'Arabica', 'L-Theanine', 'Magnesium'],
    emoji: '🍫',
    nutrition: {
      calories: 170,
      protein: '22g',
      caffeine: '200mg',
      sugar: '1g',
      sodium: '70mg',
    },
  },
  {
    id: 'electric-citrus',
    name: 'Electric Citrus',
    tagline: 'Shock The System.',
    accent: '#ca8a04',
    accentRgb: '202, 138, 4',
    canColor: '#713f12',
    labelColor: '#eab308',
    bg: '#fefce8',
    ingredients: ['Lemon', 'Ginger', 'Beta-Alanine', 'Vitamin C'],
    emoji: '⚡',
    nutrition: {
      calories: 150,
      protein: '18g',
      caffeine: '175mg',
      sugar: '0g',
      sodium: '60mg',
    },
  },
  {
    id: 'arctic-mint',
    name: 'Arctic Mint',
    tagline: 'Ice Cold Focus.',
    accent: '#0891b2',
    accentRgb: '8, 145, 178',
    canColor: '#0c4a6e',
    labelColor: '#0ea5e9',
    bg: '#f0f9ff',
    ingredients: ['Peppermint', 'L-Theanine', 'Zinc', 'Vitamin D'],
    emoji: '🧊',
    nutrition: {
      calories: 145,
      protein: '20g',
      caffeine: '165mg',
      sugar: '0g',
      sodium: '55mg',
    },
  },
]
